server:
  port: 9191
spring:
  application:
    name: product-command-service
  datasource:
    continue-on-error: true
    initialize: true
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0