server:
  port: 9293

spring:
  application:
    name: product-rating-service
  datasource:
    continue-on-error: true
    initialize: true
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:9411/

  threads:
    virtual:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
