server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: product-command-service
          uri: lb://product-command-service
          predicates:
            - Path=/product-command/**
          filters:
            - name: CircuitBreaker
              args:
                name: commandBreaker
                fallbackUri: forward:/fb/command
        - id: product-query-service
          uri: lb://product-query-service
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: queryBreaker
                fallbackUri: forward:/fb/query
    discovery:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      commandBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      queryBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      commandBreaker:
        registerHealthIndicator: true
        maxRetryAttempts: 3
        waitDuration: 10s
      queryBreaker:
        registerHealthIndicator: true
        maxRetryAttempts: 3
        waitDuration: 10s
  ratelimiter:
    instances:
      queryBreaker:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s

      commandBreaker:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
